services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loteria-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=loteriavirtual;User=root;Password=1234;"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: loteria-mysql
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: loteriavirtual
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_lc:/var/lib/mysql
      - ./Scripts/Esquema_Inicial_MODIFICADO.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_data_lc:
